[package]
name = "aichat-agent"
version = "0.30.0"
edition = "2021"
authors = ["Brandt Weary <brandt.weary@gmail.com>"]
description = "Library wrapper for AIChat agent functionality"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/Brandtweary/aichat-agent"
repository = "https://github.com/Brandtweary/aichat-agent"

[dependencies]
# Core dependencies from AIChat
anyhow = "1.0.69"
bytes = "1.4.0"
dirs = "6.0.0"
futures-util = "0.3.29"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.93", features = ["preserve_order"] }
serde_yaml = "0.9.17"
tokio = { version = "1.34.0", features = ["rt", "time", "macros", "signal", "rt-multi-thread"] }
tokio-stream = { version = "0.1.15", default-features = false, features = ["sync"] }
chrono = "0.4.23"
bincode = { version = "2.0.0", features = ["serde", "std"], default-features = false }
parking_lot = "0.12.1"
fancy-regex = "0.14.0"
base64 = "0.22.0"
nu-ansi-term = "0.50.0"
async-trait = "0.1.74"
textwrap = "0.16.0"
ansi_colours = "1.2.2"
reqwest-eventsource = "0.6.0"
simplelog = "0.12.1"
log = "0.4.20"
shell-words = "1.1.0"
sha2 = "0.10.8"
unicode-width = "0.2.0"
async-recursion = "1.1.1"
http = "1.1.0"
http-body-util = "0.1"
hyper = { version = "1.0", features = ["full"] }
hyper-util = { version = "0.1", features = ["server-auto", "client-legacy"] }
time = { version = "0.3.36", features = ["macros"] }
indexmap = { version = "2.2.6", features = ["serde"] }
hmac = "0.12.1"
aws-smithy-eventstream = "0.60.4"
urlencoding = "2.1.3"
unicode-segmentation = "1.11.0"
json-patch = { version = "4.0.0", default-features = false }
bitflags = "2.5.0"
path-absolutize = "3.1.1"
hnsw_rs = "0.3.0"
rayon = "1.10.0"
uuid = { version = "1.9.1", features = ["v4"] }
scraper = { version = "0.23.1", default-features = false, features = ["deterministic"] }
sys-locale = "0.3.1"
html_to_markdown = "0.1.0"
rust-embed = "8.5.0"
os_info = { version = "3.8.2", default-features = false }
bm25 = { version = "2.0.1", features = ["parallelism"] }
which = "8.0.0"
fuzzy-matcher = "0.3.7"
terminal-colorsaurus = "0.4.8"
duct = "1.0.0"
reedline = "0.40.0"
tempfile = "3.8"

# Note: Some dependencies might seem CLI-specific but are used by core modules
inquire = "0.7.0"
is-terminal = "0.4.9"
crossterm = "0.28.1"

[dependencies.reqwest]
version = "0.12.0"
features = ["json", "multipart", "socks", "rustls-tls", "rustls-tls-native-roots"]
default-features = false

[dependencies.syntect]
version = "5.0.0"
default-features = false
features = ["parsing", "regex-onig", "plist-load"]

[target.'cfg(target_os = "macos")'.dependencies]
crossterm = { version = "0.28.1", features = ["use-dev-tty"] }

[target.'cfg(target_os = "linux")'.dependencies]
arboard = { version = "3.3.0", default-features = false, features = ["wayland-data-control"] }

[target.'cfg(not(any(target_os = "linux", target_os = "android", target_os = "emscripten")))'.dependencies]
arboard = { version = "3.3.0", default-features = false }

[lib]
name = "aichat_agent"
path = "src/lib.rs"

[dev-dependencies]
pretty_assertions = "1.4.0"
rand = "0.9.0"
env_logger = "0.11.0"
serial_test = "3"

[[example]]
name = "math_assistant"
path = "examples/math_assistant.rs"